# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MultiRecon – Machine Learning for Multimodal Medical Image Reconstruction
email: alexandre.bousse@univ-brest.fr
description: >- # this means to ignore newlines until "baseurl:"
  MultiRecon aims at developing new image reconstruction techniques for multimodal 
  medical imaging using machine learning. MultiRecon is funded by the French National Research Agency (ANR) with grant number ANR-20-CE45-0020.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://multirecon.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minima
# remote_theme: pages-themes/slate@v0.2.0


plugins:
- jekyll-remote-theme
#   - jekyll-feed


header_pages:
- index.markdown
- team.markdown
- publications.markdown
- softwares.markdown

minima:
  skin: dark  # doesn't work yet

    # classic
    # dark
    # solarized
    # solarized-dark
